### ISSUE TITLE
Running collaborative filtering examples.

### ISSUE THREAD

**Issue by leodesigner** [arthurmensch/modl#13]
vagrant@deep-learning:~/modl$ python examples/predict_recsys.py 
Centering data
Sparsity: 0.0335217561064  X.nnz:  800167  N features:  3952  n_samples 6040
Iteration 0
('Test RMSE: ', 39.876633749822602)
Iteration 120
('Test RMSE: ', 48.440039171205285)
Iteration 720
('Test RMSE: ', 26.586114834502165)
Iteration 3630
('Test RMSE: ', 592.60091116572414)
Iteration 18110
('Test RMSE: ', 29932.618585930453)
('Final test RMSE:', 34662.550885905417)
Time : 1111.89 s

Unfortunately RMSE is increasing :(
Any suggestions ? Am I doing something wrong ?
Thanks.

**Comment by arthurmensch** [comment]
What dataset are you using ?

**Comment by leodesigner** [comment]
I had real data from user/item clicks.
It was a long time ago, I will close the issue for now.

**Comment by arthurmensch** [comment]
Ok thanks for the feedback !
