### ISSUE TITLE
error when run py.test --pyargs modl

### ISSUE THREAD

**Issue by housian1987** [arthurmensch/modl#14]
/usr/lib/python2.7/site-packages/py/_path/common.py:367: in visit 
    for x in Visitor(fil, rec, ignore, bf, sort).gen(self):
/usr/lib/python2.7/site-packages/py/_path/common.py:406: in gen
    if p.check(dir=1) and (rec is None or rec(p))])
/usr/lib/python2.7/site-packages/_pytest/main.py:676: in _recurse
    ihook = self.gethookproxy(path.dirpath())
/usr/lib/python2.7/site-packages/_pytest/main.py:587: in gethookproxy
    my_conftestmodules = pm._getconftestmodules(fspath)
/usr/lib/python2.7/site-packages/_pytest/config.py:339: in _getconftestmodules
    mod = self._importconftest(conftestpath)
/usr/lib/python2.7/site-packages/_pytest/config.py:364: in _importconftest
    raise ConftestImportFailure(conftestpath, sys.exc_info())
E   ConftestImportFailure: ImportError('No module named concurrent.futures',)
E     File "/usr/lib64/python2.7/site-packages/modl/__init__.py", line 1, in <module>
E       from .dict_fact import DictFact
E     File "/usr/lib64/python2.7/site-packages/modl/dict_fact.py", line 1, in <module>
E       from concurrent.futures import ThreadPoolExecutor

**Comment by arthurmensch** [comment]
This package is only compatible with Python 3
