### ISSUE TITLE
dowload datasets

### ISSUE THREAD

**Issue by furas** [arthurmensch/modl#21]
Commands

    make download-movielens1m

    make download-movielens10m

can't download datasets. 

They give error `404` for urls

 [http://www.mblondel.org/data/movielens1m.tar.bz2]( http://www.mblondel.org/data/movielens1m.tar.bz2)
[http://www.mblondel.org/data/movielens10m.tar.bz2](http://www.mblondel.org/data/movielens10m.tar.bz2)

**Comment by litxiaoyao** [comment]
I have encountered this problem too...

**Comment by bthirion** [comment]
Sorry, but we're no longer supporting such features. I guess that these data are available somewhere. You may want to contact M.Blondel. Best,
