### ISSUE TITLE
enet_projection in dictionary update: hack or not hack ?

### ISSUE THREAD

**Issue by dohmatob** [arthurmensch/modl#7]
The code from lines [604 to 622 of dict_fact.py ](https://github.com/arthurmensch/modl/blob/master/modl/dict_fact.py#L604) is really weird. Are we formally computing the projection of the atom onto the elastic-net unit ball of radius 1 or is it some kind of hack ? For example, the call to `enet_projection` has `radius=self.comp_norm_[k]`.

In any case, a detailed comment explaining what is being done would help for future maintenance / extension.

**Comment by arthurmensch** [comment]
It's the right form : see the dictionary update section of https://arxiv.org/abs/1701.05363
