### ISSUE TITLE
setup install fails for cython < 0.25

### ISSUE THREAD

**Issue by dohmatob** [arthurmensch/modl#9]
`python setup.py install` fails with error message

`
error: Command "gcc -pthread -fno-strict-aliasing -g -O2 -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/volatile/home/edohmato/anaconda2/lib/python2.7/site-packages/numpy/core/include -I/volatile/home/edohmato/anaconda2/lib/python2.7/site-packages/numpy/core/include -I/volatile/home/edohmato/anaconda2/include/python2.7 -c modl/utils/math/enet.c -o build/temp.linux-x86_64-2.7/modl/utils/math/enet.o" failed with exit status 1
`

For the record, upgrading cython (e.g `pip install cython --upgrade`) to latest version (0.25.2) fixes the problem.

**Comment by arthurmensch** [comment]
I guess that comes from fuse types. I will update requirements.txt

**Comment by arthurmensch** [comment]
Solved
